import type { FlightOffer, Policy, StayOffer } from "./types";

export const ORGANIZATION_POLICY: Policy = {
  id: "policy-org-default",
  scope: "organization",
  name: "Política padrão da organização",
  rules: [
    {
      id: "rule-flight-cabin",
      field: "cabinClass",
      operator: "in",
      value: ["economy", "premium_economy"],
      appliesTo: "flight",
      description: "Classe econômica ou premium economy",
    },
    {
      id: "rule-flight-price",
      field: "totalAmount",
      operator: "lte",
      value: 3000,
      appliesTo: "flight",
      description: "Até R$ 3.000 por passagem",
    },
    {
      id: "rule-stay-stars",
      field: "starRating",
      operator: "lte",
      value: 4,
      appliesTo: "stay",
      description: "Até 4 estrelas",
    },
    {
      id: "rule-stay-price",
      field: "totalAmount",
      operator: "lte",
      value: 1200,
      appliesTo: "stay",
      description: "Até R$ 1.200 na diária total",
    },
  ],
};

export const MOCK_FLIGHT_OFFERS: FlightOffer[] = [
  {
    id: "flt-1",
    mode: "flight",
    origin: "GRU",
    destination: "JFK",
    destinationCountry: "US",
    departureAt: "2026-08-10T22:30:00.000Z",
    returnAt: "2026-08-17T23:10:00.000Z",
    cabinClass: "economy",
    airline: "LATAM",
    stops: 1,
    refundable: false,
    totalAmount: 2850,
    currency: "BRL",
  },
  {
    id: "flt-2",
    mode: "flight",
    origin: "GRU",
    destination: "MIA",
    destinationCountry: "US",
    departureAt: "2026-08-12T09:15:00.000Z",
    returnAt: "2026-08-19T18:40:00.000Z",
    cabinClass: "business",
    airline: "American Airlines",
    stops: 0,
    refundable: true,
    totalAmount: 8200,
    currency: "BRL",
  },
  {
    id: "flt-3",
    mode: "flight",
    origin: "GRU",
    destination: "GIG",
    destinationCountry: "BR",
    departureAt: "2026-08-05T07:00:00.000Z",
    returnAt: "2026-08-06T20:00:00.000Z",
    cabinClass: "economy",
    airline: "Azul",
    stops: 0,
    refundable: false,
    totalAmount: 450,
    currency: "BRL",
  },
  {
    id: "flt-4",
    mode: "flight",
    origin: "GRU",
    destination: "EZE",
    destinationCountry: "AR",
    departureAt: "2026-08-20T13:20:00.000Z",
    returnAt: "2026-08-23T21:00:00.000Z",
    cabinClass: "premium_economy",
    airline: "LATAM",
    stops: 0,
    refundable: false,
    totalAmount: 3400,
    currency: "BRL",
  },
  {
    id: "flt-5",
    mode: "flight",
    origin: "GRU",
    destination: "LIS",
    destinationCountry: "PT",
    departureAt: "2026-09-02T21:45:00.000Z",
    returnAt: "2026-09-12T14:30:00.000Z",
    cabinClass: "business",
    airline: "TAP Air Portugal",
    stops: 1,
    refundable: true,
    totalAmount: 6700,
    currency: "BRL",
  },
  {
    id: "flt-6",
    mode: "flight",
    origin: "CGH",
    destination: "BSB",
    destinationCountry: "BR",
    departureAt: "2026-08-14T08:10:00.000Z",
    returnAt: "2026-08-15T19:50:00.000Z",
    cabinClass: "economy",
    airline: "Gol",
    stops: 0,
    refundable: false,
    totalAmount: 620,
    currency: "BRL",
  },
];

export const MOCK_STAY_OFFERS: StayOffer[] = [
  {
    id: "sty-1",
    mode: "stay",
    city: "São Paulo",
    country: "BR",
    checkIn: "2026-08-10",
    checkOut: "2026-08-13",
    hotelName: "Ibis Budget Paulista",
    starRating: 2,
    refundable: true,
    totalAmount: 480,
    currency: "BRL",
  },
  {
    id: "sty-2",
    mode: "stay",
    city: "Nova York",
    country: "US",
    checkIn: "2026-08-10",
    checkOut: "2026-08-17",
    hotelName: "The Plaza",
    starRating: 5,
    refundable: false,
    totalAmount: 7200,
    currency: "BRL",
  },
  {
    id: "sty-3",
    mode: "stay",
    city: "Rio de Janeiro",
    country: "BR",
    checkIn: "2026-08-05",
    checkOut: "2026-08-06",
    hotelName: "Windsor Atlântica",
    starRating: 4,
    refundable: true,
    totalAmount: 980,
    currency: "BRL",
  },
  {
    id: "sty-4",
    mode: "stay",
    city: "Lisboa",
    country: "PT",
    checkIn: "2026-09-02",
    checkOut: "2026-09-12",
    hotelName: "Hotel Avenida Palace",
    starRating: 5,
    refundable: false,
    totalAmount: 2100,
    currency: "BRL",
  },
];

export const MOCK_OFFERS = [...MOCK_FLIGHT_OFFERS, ...MOCK_STAY_OFFERS];
